Implement p1 tasks
unr-deaddrop/prototype_backend pull request #5
Opened 2023-12-30 00:33 UTC by Arellano-Jann

FINISHED:
Implement coherent redirects to Django admin site from Svelte
Implement task detail view
Implement task listing view
Implement endpoint detail view
Implement endpoint listing view
Implement protocol detail view
Implement protocol listing view
Implement agent detail view
Implement agent listing view

BLOCKED:
Make it possible to delete endpoints
Implement payload generation form

IN PROGRESS:
Implement log view

2023-12-30 07:19 UTC, lgactna requested changes

2023-12-30 07:19 UTC, lgactna commented on .gitignore
> +None/
what's this? (add a comment to the gitignore about why we're ignoring this and when this directory gets created)

2023-12-30 07:19 UTC, lgactna commented on backend/connections.txt
not rlly important but i'd change this to a markdown file so it's more obvious this isn't intended to be used by any part of the system, it's just a human-readable file for notes

2023-12-30 07:19 UTC, lgactna commented on backend/models.py
it should be the case that `/deaddrop/settings.py` declares [`MEDIA_ROOT`](https://docs.djangoproject.com/en/5.0/ref/settings/#media-root) to decide where uploaded files go, rather than the (technically) correct assumption that `upload_to` defaults to being rooted at the project root (i.e. the way it is right now)

i got a little confused at the double-nested `files/files` at first (just a nitpick) but i'd prefer that you do something like declaring `MEDIA_ROOT = "uploads"` in `settings.py` and then dropping the leading `files/` from all of your `upload_to` parameters for `FileField`

there are other reasons to prefer `MEDIA_ROOT` calling the shots rather than assuming `MEDIA_ROOT = "."`, but explicitly declaring `MEDIA_ROOT` means we can refer to it as a global setting in the future if needed

2023-12-30 07:19 UTC, lgactna commented on backend/models.py
> +    # this may be wrong according to https://stackoverflow.com/questions/39821723/django-rest-framework-many-to-many-field-related-to-itself
consider leading this comment with a `FIXME:` or a `TODO:` or smth, makes it easier to find if it turns out we have some inexplicable problem later on

2023-12-30 07:19 UTC, lgactna commented on backend/models.py
> +    definition_path = models.FileField(upload_to="files/agents", max_length=100)
i dont know how high i was when i wrote these model definitions but there should not be a `max_length` on these lmao

2023-12-30 07:19 UTC, lgactna commented on backend/models.py
> +    #     return self.timestamp # this doesn't work and causes log to bug
what happens if this is uncommented?

2023-12-30 07:19 UTC, lgactna commented on backend/workflows.txt
ditto with above, make this a markdown file

2023-12-30 07:59 UTC, lgactna commented
Affects:
- https://github.com/unr-deaddrop/frontend/issues/19 
- https://github.com/unr-deaddrop/frontend/issues/21
- https://github.com/unr-deaddrop/frontend/issues/22
- https://github.com/unr-deaddrop/frontend/issues/23
- https://github.com/unr-deaddrop/frontend/issues/24
- https://github.com/unr-deaddrop/frontend/issues/25
- https://github.com/unr-deaddrop/frontend/issues/26
- https://github.com/unr-deaddrop/frontend/issues/27
- https://github.com/unr-deaddrop/frontend/issues/28
- https://github.com/unr-deaddrop/frontend/issues/29

2024-01-03 01:23 UTC, Arellano-Jann commented on .gitignore
> +None/
it's the image directory, i'll clean it up now since the image directory isn't "none" anymore

2024-01-03 07:33 UTC, lgactna approved these changes
see comment, otherwise looks great to me

2024-01-03 07:33 UTC, lgactna commented on .gitignore
> +media/
consider adding a comment that mentions this is equal to MEDIA_ROOT in django's settings

2024-01-04 01:54 UTC, lgactna commented on .gitignore
> +media/
deferred for #7

2024-01-04 01:54 UTC, merged